### ISSUE TITLE
Supervised training issue

### ISSUE THREAD

**Issue by asnt** [ThibaultGROUEIX/3D-CODED#11]
Thanks for sharing this great work.

I am trying to train the supervised model but it seems not to converge. Generated shapes are scaled down too much, as in this image:
![3dcoded_train_sup](https://user-images.githubusercontent.com/830589/60615867-70a30100-9dd0-11e9-87c0-ca1c3a044659.png)

I modified the data generation process to use trimesh for loading/saving. To me, the generated scans look similar to the template in orientation and scale (see image above).
However, I only generated half of the suggested dataset size (115000 meshes instead of 230000). Would this be an issue?

Any other hint?

**Comment by ThibaultGROUEIX** [comment]
Dear @asnt,
You definitely have an issue here. It seems that the scale of the input and output are completely different. It looks like the network is collapsing the output toward 0.
My best bet :  Make sure Trimesh loads meshes without pre-processing with the flag "process=False". Trimesh preprocessing shuffle the vertices order and the labels for supervised training become random noise.
Each point is matched with a random point in the target and the network then tends to generate an average, so that would explain why you get 0s.
Additionally, I will release my own train and test files on **monday** to make sure you can reproduce exactly the same thing as me.

**Comment by asnt** [comment]
`process=False` solved the issue. The early training outputs seem to make more sense now.

Thanks for your quick reply @ThibaultGROUEIX
